title: LegacyBoost
description: Ship Legacy Code 5x Faster Without Risky Rewrites
baseurl: ""
url: ""

# Theme settings - using minimal theme for a cleaner look
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Navigation
nav:
  - title: Home
    url: /
  - title: Features
    url: /features
  - title: Pricing
    url: /pricing
  - title: About
    url: /about

# Build settings
markdown: kramdown
